steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "version"
    entrypoint: "/bin/bash"
    args: [ "-c", "echo $TAG_NAME | awk -F'/' '{print $2}' > _TAG" ]

  - name: "gcr.io/cloud-builders/docker"
    id: "build"
    entrypoint: "/bin/bash"
    env:
      - '_SERVICE_DOCKER_DIR_OVERRIDE=$_SERVICE_DOCKER_DIR_OVERRIDE'
      - '_SERVICE=$_SERVICE'
    args: [ "-c", "docker build -t gcr.io/$PROJECT_ID/$_SERVICE:latest -t gcr.io/$PROJECT_ID/$_SERVICE:$(cat _TAG) -f cmd/${_SERVICE_DOCKER_DIR_OVERRIDE:-$$_SERVICE}/Dockerfile ." ]

  - name: "gcr.io/cloud-builders/docker"
    id: "publish-version"
    entrypoint: "/bin/bash"
    args: [ "-c", "docker push gcr.io/$PROJECT_ID/$_SERVICE:$(cat _TAG)" ]

  - name: "gcr.io/cloud-builders/docker"
    id: "publish-latest"
    entrypoint: "/bin/bash"
    args: [ "-c", "docker push gcr.io/$PROJECT_ID/$_SERVICE:latest" ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy"
    entrypoint: "kubectl"
    args: ["set image deployment $_SERVICE $_SERVICE=gcr.io/$PROJECT_ID/$_SERVICE:$(cat _TAG)"]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=tenderly-container-cluster'
