---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenderly-geth
  labels:
    app: tenderly-geth
spec:
  selector:
    matchLabels:
      app: tenderly-geth
  replicas: 1
  template:
    metadata:
      labels:
        app: tenderly-geth
    spec:
      containers:
        - name: tenderly-geth
          image: gcr.io/tenderly-project/tenderly-geth:latest
          command: ["/app/build/bin/geth"]
          args: ["--goerli", "--datadir", "5", "--syncmode", "full", "--gcmode", "archive", "--cache", "4096", "--rpc", "--rpcaddr", "0.0.0.0", "--rpcapi", "eth,net,web3,admin,debug,personal,txpool", "--rpccorsdomain", "*", "--rpcvhosts", "*"]
          env:
            - name: "FDB_CLUSTER_FILE"
              value: "/mnt/config-volume/cluster-file"
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/var/run/secrets/cloud.google.com/service-account.json"
            - name: "PROJECT_ID"
              value: "tenderly-project"
          resources:
            requests:
              cpu: 1
            limits:
              cpu: 2
          ports:
            - name: rpc
              containerPort: 8545
            - name: node
              containerPort: 30303
          volumeMounts:
            - name: service-account
              mountPath: "/var/run/secrets/cloud.google.com"
            - name: config-volume
              mountPath: "/mnt/config-volume"
      volumes:
        - name: service-account
          secret:
            secretName: tenderly-server-service-account
        - name: config-volume
          configMap:
            name: fdb-cluster-config
